# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20151216_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='creation_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='creation_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='creation_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(),
        ),
    ]
