# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-02 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_auto_20151126_0905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='name',
            new_name='description',
        ),
    ]
