# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_auto_20151230_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
