# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_auto_20160103_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='description',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
