# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 23:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_auto_20160314_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='type',
        ),
    ]
