# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='login_counter',
            field=models.IntegerField(default=0),
        ),
    ]
