# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0005_userprofile_login_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='login_counter',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
